[client]
toolbarMode = "minimal"
showErrorDetails = false
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25

[theme]
primaryColor = "#00A896"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0B2545"
font = "sans serif"
